# REstrictedAreaAura by Civalo
# Spigot URL:   Github:  
# License: GNU Lesser General Public License v3  
debug: false
max_radius: 50
messages:
   prefix: '[Restricted] '
   restricted: 'You do not have permission to be in this area.'