name: RestrictedAreaAura
main: com.civservers.plugins.restrictedAreaAura.RestrictedAreaAura
#com.example.plugins.MyPlugin
version: 0.0.1

author: "Civalo"
commands:
   restrictedareaaura:
      description: This is a demo command. (no requirements)
      aliases: [raa]
      usage: 
      permission: 
      permission-message: "You don't have <permission>"